name: app
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^13.1.0
  http: ^1.2.0
  shared:
    path: ../shared
  shared_preferences: ^2.2.2

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
