name: api
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  pointycastle: ^3.7.4
  postgres: ^3.0.7
  shared:
    path: ../shared
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4

dev_dependencies:
  very_good_analysis: ^5.1.0
